#!/usr/bin/env python3
"""Generate lib/math.mcaml — Q16.16 transcendental library for MCaml.

The generated file contains top-level `val` global arrays (populated
once at datapack load via Phase G) holding precomputed lookup tables,
plus user-facing functions that combine range reduction with LUT
lookups.

Q16.16 encoding: x_real * 65536 = x_encoded (int32).

Phase Math v1 covers:
  - exp_fixed via int_exp_lut[n] * frac_exp_lut[k]
      where x_encoded = n*65536 + f, k = f/256
  - log_fixed (Math1 half-two — planned, not yet implemented)
  - sigmoid/tanh/gelu (Math2 — planned)
  - tensor primitives (Math3 — planned)

Run with `python3 tools/gen_math_lut.py -o lib/math.mcaml` to
regenerate. Check in both the generator AND the generated file so
the LUT is reproducible but compilation doesn't depend on the
Python toolchain.
"""
from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path


Q16_SCALE = 65536


def q16(x: float) -> int:
    """Round a real to its Q16.16 int encoding. Raises if out of range."""
    scaled = round(x * Q16_SCALE)
    if scaled < -2**31 or scaled >= 2**31:
        raise ValueError(f"value {x!r} out of Q16.16 range")
    return scaled


# ----- exp LUTs ---------------------------------------------------------
#
# exp(x) for x >= 0, x < 10.4 (Q16.16 saturation boundary).
# Decompose x_encoded = n*65536 + f, where n is the integer part
# (0 <= n <= 10) and f is the fractional raw (0 <= f < 65536).
# Then exp(x) = exp(n) * exp(f / 65536).
#
# int_exp_lut[n]  = Q16.16 encoding of exp(n) for n = 0..10.
#   exp(10) ~ 22026, fits in Q16.16 (max real ~32768). exp(11) ~ 59874
#   overflows — 10 is the hard max.
#
# frac_exp_lut[k] = Q16.16 encoding of exp(k/256) for k = 0..255.
#   Domain [1, e) ~ [1.0, 2.7183). All fit easily.
#   Note: exp_fixed indexes with k = (x mod 65536) / 256, which drops
#   the bottom 8 bits of the fractional part. The resulting value is
#   always exp(floor(f/256) / 256), NOT exp(f/65536), so there's a
#   small systematic bias within each 256-wide bucket. For nearest-
#   entry rounding the bias is at most ~exp(1/512) - 1 ~ 0.002 relative,
#   which matches Q16.16's precision floor anyway. Upgrade to linear
#   interpolation if a workload demands tighter bounds (+~8 cmds/call).

INT_EXP_MAX = 10   # highest safe integer exponent (exp(11) would overflow)
FRAC_EXP_N  = 256  # LUT length; k in [0, 255] maps f/256

def build_int_exp_lut() -> list[int]:
    return [q16(math.exp(n)) for n in range(INT_EXP_MAX + 1)]


def build_frac_exp_lut() -> list[int]:
    return [q16(math.exp(k / FRAC_EXP_N)) for k in range(FRAC_EXP_N)]


# ----- emission ---------------------------------------------------------

PREAMBLE = """(* lib/math.mcaml — Q16.16 transcendental library for MCaml.

   AUTOMATICALLY GENERATED by tools/gen_math_lut.py.
   DO NOT EDIT DIRECTLY — regenerate with `python3 tools/gen_math_lut.py`.

   Q16.16 encoding: x_real * 65536 = x_encoded (int).
   All functions operate on and return Q16.16 values (type float).

   LUTs:
     int_exp_lut[n]  = exp(n)      for n in [0, 10]   (11 entries)
     frac_exp_lut[k] = exp(k/256)  for k in [0, 255]  (256 entries)

   Functions:
     exp_fixed x     = exp(x) for real x, saturating near 10.4
*)

"""

EXP_FIXED_BODY = """\
(* exp_fixed(x) : float = exp(x) as Q16.16.

   Algorithm:
     - For negative x, return 1/exp(|x|) via one fdiv.
     - For non-negative x, decompose x_encoded = n*65536 + f with
       n = to_int(x) (integer part) and f = x mod 65536 (fractional
       raw). Then exp(x) = exp(n) * exp(f/65536), which we approximate
       with int_exp_lut[n] * frac_exp_lut[f/256].
     - n > 10 saturates to exp(10) * frac_exp_lut[255] (~22025.4 * ~2.71
       ~= 59800, just under Q16.16 overflow). Callers needing the full
       Q16.16 ceiling must clamp before calling.

   Cost: ~20 cmds for the positive fast path (see §13.4 correction).
         Negative path adds ~10 cmds for the fdiv + recursion unfold. *)

(* exp_fixed(x) = exp(x) as Q16.16.

   PRECONDITION: 0.0 <= x < 10.0. For x outside this range the result
   is nonsense (negative x would LUT-index with a negative int; x >= 10
   would index past int_exp_lut[10]).

   Callers with negative arguments should compute it themselves:
     fdiv(1.0, exp_fixed(neg_f(x)))
   MineTorch's softmax path always negates beforehand so this is not
   a usability burden for the primary client; human users who want a
   polymorphic wrapper can write one at their layer.

   Cost: ~25 cmds per call (positive branch only, no conditional
   dispatch overhead). Precision: ~0.1-0.2% worst case from pre-shift
   fmul plus LUT frac truncation (drops bottom 8 bits of the
   fractional raw). Callers needing <0.01% should linear-interpolate
   between adjacent frac_exp_lut entries (~+8 cmds). *)
fun exp_fixed (x: float) : float =
  let x_raw = raw_of_float(x) in
  let n = x_raw / 65536 in
  let k = (x_raw % 65536) / 256 in
  let ei = int_exp_lut[n] in
  let ef = frac_exp_lut[k] in
  fmul(ei, ef)
"""


def to_float_literal(encoded: int) -> str:
    """Render a Q16.16 int as a Python float literal that round-trips
    exactly back to the same encoded int under MCaml's
    `round(f *. 65536)` encoding in knormal. Divisions by 65536 are
    exact in IEEE-754 doubles for |encoded| < 2^47, and multiplying
    the quotient back by 65536 returns the original int exactly, so
    re-encoding via round() never shifts. This is what lets us declare
    the LUTs as `val foo = [| ... |]` with float literals — MCaml's
    typer infers TArrStatic(TFloat, N), subscripts return TFloat, and
    fmul accepts the result without a cast. """
    return repr(encoded / Q16_SCALE)


def emit(output_path: Path | None) -> None:
    int_exp = build_int_exp_lut()
    frac_exp = build_frac_exp_lut()

    buf: list[str] = [PREAMBLE]

    buf.append("val int_exp_lut = [|\n")
    buf.append("  " + "; ".join(to_float_literal(v) for v in int_exp) + "\n")
    buf.append("|]\n\n")

    buf.append("val frac_exp_lut = [|\n")
    # Wrap at 6 per line for readability (float literals are wider).
    line: list[str] = []
    for i, v in enumerate(frac_exp):
        line.append(to_float_literal(v))
        if len(line) == 6:
            suffix = ";" if i < len(frac_exp) - 1 else ""
            buf.append("  " + "; ".join(line) + suffix + "\n")
            line = []
    if line:
        buf.append("  " + "; ".join(line) + "\n")
    buf.append("|]\n\n")

    buf.append(EXP_FIXED_BODY)

    text = "".join(buf)
    if output_path is None:
        sys.stdout.write(text)
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(text)
        print(f"wrote {output_path} ({len(int_exp)} int + {len(frac_exp)} frac entries)")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", type=Path, default=None,
                    help="output file path (default: stdout)")
    args = ap.parse_args()
    emit(args.output)


if __name__ == "__main__":
    main()
